### ISSUE TITLE
2FA Errors

### ISSUE THREAD

**Issue by GeekLucanis** [dosdude1/discord-lite#41] opened 2024-11-20 07:04 UTC
The client will not accept any of the 2FA codes, and will also log me out of all instances of Discord on every attempt. 
I am running 10.5.8 with brew and all xcode, on a 11,2 PowerMac G5

**Comment by eimi-codes** [comment] 2024-11-20 18:35
Same error on PPC Tiger 10.4.11

**Comment by dosdude1** [comment] 2024-11-21 07:37
Currently being worked on. The cause if the issue has been found, and I'll have it fixed very soon.

**Comment by dosdude1** [comment] 2024-11-22 00:10
Should now be resolved with latest release. Once confirmed, I'll close the issue.

**Comment by GeekLucanis** [comment] 2024-11-22 00:53
Issue resolved.

**Closed** 2024-11-22 02:25 UTC
